artifact_location: file:///D:/Neural_Networks/Kaggle/street_food_classifier/mlflow/742854679818458359
creation_time: 1748870166069
experiment_id: '742854679818458359'
last_update_time: 1748870166069
lifecycle_stage: active
name: street_food_classification
